import type { UserActivityRecord } from '@/types/activity';
import { SRS_PAGE_REFERENCE } from '@/lib/interface-names';
import { anchorDateTime } from './anchor';

/**
 * Seeded user activity records so the Administration view is not empty on first
 * use. New records are appended by MockTdmsClient for every action the SRS
 * requires (LOG-01).
 */
export const MOCK_ACTIVITY_RECORDS: UserActivityRecord[] = [
  {
    activityRecordNumber: 'ACT-000001',
    dateTime: anchorDateTime(-5, 8, 30),
    userReference: 'wasim.ahmed@aibtglobal.edu.au',
    accessLevel: 'SUPER_ADMIN',
    assignment: null,
    pageOrFunction: SRS_PAGE_REFERENCE.login,
    action: 'Sign in',
    recordOrBatchReference: 'usr-0001',
    result: 'Access granted',
    technicalReference: 'corr-demo-0001',
    plainLanguageDetail: 'Microsoft sign-in succeeded and the TDMS account is active with an approved access level.',
  },
  {
    activityRecordNumber: 'ACT-000002',
    dateTime: anchorDateTime(-5, 8, 46),
    userReference: 'sophia.nguyen@aibtglobal.edu.au',
    accessLevel: 'DATA_EDITOR',
    assignment: 'STUDENT_DATA_OFFICER',
    pageOrFunction: SRS_PAGE_REFERENCE.singleStudentEntry,
    action: 'Create',
    recordOrBatchReference: 'ST20261024',
    result: 'Completed',
    plainLanguageDetail: 'Student record created after preview and confirmation.',
  },
  {
    activityRecordNumber: 'ACT-000003',
    dateTime: anchorDateTime(-4, 10, 12),
    userReference: 'ankit.kumar@aibtglobal.edu.au',
    accessLevel: 'DATA_EDITOR',
    assignment: 'TIMETABLE_OFFICER',
    pageOrFunction: SRS_PAGE_REFERENCE.timetable,
    action: 'Timetable save',
    recordOrBatchReference: 'TT-00004',
    result: 'Completed',
    plainLanguageDetail: 'Timetable record saved after validation passed with no blocking issue.',
  },
  {
    activityRecordNumber: 'ACT-000004',
    dateTime: anchorDateTime(-4, 11, 2),
    userReference: 'ankit.kumar@aibtglobal.edu.au',
    accessLevel: 'DATA_EDITOR',
    assignment: 'TIMETABLE_OFFICER',
    pageOrFunction: SRS_PAGE_REFERENCE.trainerData,
    action: 'Export',
    recordOrBatchReference: '12 rows',
    result: 'Completed',
    plainLanguageDetail: 'Filtered trainer result exported to CSV.',
  },
  {
    activityRecordNumber: 'ACT-000005',
    dateTime: anchorDateTime(-3, 9, 24),
    userReference: 'rebecca.lawson@aibtglobal.edu.au',
    accessLevel: 'ADMIN',
    assignment: null,
    pageOrFunction: SRS_PAGE_REFERENCE.bulkStudentImport,
    action: 'Import',
    recordOrBatchReference: 'BATCH-000001',
    result: 'Completed',
    plainLanguageDetail: 'Bulk student import saved. Inserted 95, excluded 2, duplicate 1, unmatched 0.',
  },
  {
    activityRecordNumber: 'ACT-000006',
    dateTime: anchorDateTime(-3, 15, 40),
    userReference: 'Unmatched user',
    accessLevel: 'Unknown',
    assignment: null,
    pageOrFunction: SRS_PAGE_REFERENCE.login,
    action: 'Access denied',
    recordOrBatchReference: '—',
    result: 'Access denied',
    technicalReference: 'corr-demo-0006',
    plainLanguageDetail:
      'Sign-in did not return a verified identity. No TDMS session was created and no password was stored.',
  },
  {
    activityRecordNumber: 'ACT-000007',
    dateTime: anchorDateTime(-2, 13, 8),
    userReference: 'sophia.nguyen@aibtglobal.edu.au',
    accessLevel: 'DATA_EDITOR',
    assignment: 'STUDENT_DATA_OFFICER',
    pageOrFunction: SRS_PAGE_REFERENCE.singleStudentEntry,
    action: 'Delete',
    recordOrBatchReference: 'ST20260998',
    reason: 'INCORRECT_OR_DUPLICATE_RECORD',
    result: 'Completed',
    plainLanguageDetail: 'Student record moved to the recycle area with a recovery deadline 14 days later.',
  },
  {
    activityRecordNumber: 'ACT-000008',
    dateTime: anchorDateTime(-1, 9, 5),
    userReference: 'ankit.kumar@aibtglobal.edu.au',
    accessLevel: 'DATA_EDITOR',
    assignment: 'TIMETABLE_OFFICER',
    pageOrFunction: SRS_PAGE_REFERENCE.login,
    action: 'Sign in',
    recordOrBatchReference: 'usr-0002',
    result: 'Access granted',
    technicalReference: 'corr-demo-0008',
    plainLanguageDetail: 'Microsoft sign-in succeeded and the TDMS account is active with an approved access level.',
  },
];
