"""initial tdms schema v1

Revision ID: 6266b57ea53e
Revises: 
Create Date: 2026-08-10 19:04:11.244525

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6266b57ea53e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # MANUAL ADDITION 1 of 3 - Alembic autogenerate cannot emit extensions.
    # `citext` is required by users.organisation_email, students.college_email
    # and students.personal_email. Without it CREATE TABLE fails outright.
    # Case-insensitive uniqueness is what stops A.Person@... and a.person@...
    # becoming two accounts (AUTH-04).
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campus_code', sa.Text(), nullable=False),
    sa.Column('campus_name', sa.Text(), nullable=False),
    sa.Column('campus_location', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campuses')),
    sa.UniqueConstraint('campus_code', name=op.f('uq_campuses_campus_code'))
    )
    op.create_table('colleges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('college_short_name', sa.Text(), nullable=False),
    sa.Column('college_full_name', sa.Text(), nullable=False),
    sa.Column('email_domain', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colleges')),
    sa.UniqueConstraint('college_short_name', name=op.f('uq_colleges_college_short_name'))
    )
    op.create_table('course_statuses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('selectable_for_new_records', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_statuses')),
    sa.UniqueConstraint('code', name=op.f('uq_course_statuses_code'))
    )
    op.create_table('qualifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('qualification_code', sa.Text(), nullable=False),
    sa.Column('qualification_title', sa.Text(), nullable=False),
    sa.Column('course_level', sa.Text(), nullable=True),
    sa.Column('field_of_education_broad', sa.Text(), nullable=True),
    sa.Column('field_of_education_narrow', sa.Text(), nullable=True),
    sa.Column('course_sector', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('qualification_code', name=op.f('uq_qualifications_qualification_code'))
    )
    op.create_table('reason_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('requires_detail', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reason_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_reason_codes_code'))
    )
    op.create_table('units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('unit_code', sa.Text(), nullable=False),
    sa.Column('unit_title', sa.Text(), nullable=False),
    sa.Column('uoc_type', sa.Enum('THEORY', 'THEORY_AND_PRACTICAL', name='uoc_type'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('unit_code', name=op.f('uq_units_unit_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entra_object_id', sa.UUID(), nullable=True),
    sa.Column('entra_tenant_id', sa.UUID(), nullable=True),
    sa.Column('organisation_email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('access_level', sa.Enum('DATA_EDITOR', 'ADMIN', 'SUPER_ADMIN', name='access_level'), nullable=False),
    sa.Column('data_editor_assignment', sa.Enum('STUDENT_DATA_OFFICER', 'TIMETABLE_OFFICER', name='data_editor_assignment'), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_editor_assignment IS NULL OR access_level = 'DATA_EDITOR'", name=op.f('ck_users_assignment_only_for_data_editor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('entra_object_id', name=op.f('uq_users_entra_object_id')),
    sa.UniqueConstraint('organisation_email', name=op.f('uq_users_organisation_email'))
    )
    op.create_table('college_campuses',
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_college_campuses_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_college_campuses_college_id_colleges'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('college_id', 'campus_id', name=op.f('pk_college_campuses'))
    )
    op.create_table('facilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('facility_reference', sa.Text(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_type', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_facilities_capacity_positive')),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_facilities_campus_id_campuses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities')),
    sa.UniqueConstraint('campus_id', 'facility_reference', name='uq_facilities_campus_id_facility_reference')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_reference', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=True),
    sa.Column('excluded_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=True),
    sa.Column('corrected_count', sa.Integer(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_import_batches_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('batch_reference', name=op.f('uq_import_batches_batch_reference'))
    )
    op.create_table('qualification_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('qualification_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_qualification_units_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_qualification_units_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_qualification_units_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('fk_qualification_units_qualification_id_qualifications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_qualification_units_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualification_units')),
    sa.UniqueConstraint('qualification_id', 'delivery_order', deferrable=True, initially='DEFERRED', name='uq_qualification_units_qualification_id_delivery_order'),
    sa.UniqueConstraint('qualification_id', 'unit_id', name='uq_qualification_units_qualification_id_unit_id')
    )
    op.create_table('reason_code_contexts',
    sa.Column('reason_code_id', sa.BigInteger(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_codes.id'], name=op.f('fk_reason_code_contexts_reason_code_id_reason_codes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reason_code_id', 'context', name=op.f('pk_reason_code_contexts'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.Text(), nullable=False),
    sa.Column('trainer_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_trainers_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_trainers_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_trainers_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers')),
    sa.UniqueConstraint('trainer_id', name=op.f('uq_trainers_trainer_id'))
    )
    op.create_table('user_activity_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_reference_snapshot', sa.Text(), nullable=False),
    sa.Column('access_level_snapshot', sa.Enum('DATA_EDITOR', 'ADMIN', 'SUPER_ADMIN', name='access_level'), nullable=True),
    sa.Column('assignment_snapshot', sa.Enum('STUDENT_DATA_OFFICER', 'TIMETABLE_OFFICER', name='data_editor_assignment'), nullable=True),
    sa.Column('page_or_function', sa.Text(), nullable=False),
    sa.Column('action', sa.Enum('SIGN_IN', 'SIGN_OUT', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'IMPORT', 'EXPORT', 'TIMETABLE_SAVE', 'TIMETABLE_GENERATION', 'CANCELLATION_AFTER_UPDATE', 'OVERRIDE', 'ACCESS_DENIED', name='activity_action'), nullable=False),
    sa.Column('record_reference', sa.Text(), nullable=True),
    sa.Column('reason_code_id', sa.BigInteger(), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('COMPLETED', 'REJECTED_BY_VALIDATION', 'CANCELLED_BY_USER', 'FAILED_SYSTEM_ERROR', name='activity_result'), nullable=True),
    sa.Column('microsoft_sign_in_result', sa.Enum('SUCCESS', 'FAILURE', name='ms_sign_in_result'), nullable=True),
    sa.Column('tdms_access_decision', sa.Enum('GRANTED', 'DENIED', name='access_decision'), nullable=True),
    sa.Column('technical_reference', sa.Text(), nullable=True),
    sa.Column('plain_language_detail', sa.Text(), nullable=False),
    sa.CheckConstraint('result IS NOT NULL OR microsoft_sign_in_result IS NOT NULL OR tdms_access_decision IS NOT NULL', name=op.f('ck_user_activity_records_outcome_present')),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_codes.id'], name=op.f('fk_user_activity_records_reason_code_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_records_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_records'))
    )
    op.create_index('ix_user_activity_records_occurred_at', 'user_activity_records', ['occurred_at'], unique=False)
    op.create_index('ix_user_activity_records_user_id_occurred_at', 'user_activity_records', ['user_id', 'occurred_at'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('qualification_id', sa.BigInteger(), nullable=False),
    sa.Column('course_code', sa.Text(), nullable=False),
    sa.Column('course_status_id', sa.BigInteger(), nullable=False),
    sa.Column('total_course_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_course_offerings_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['college_id', 'campus_id'], ['college_campuses.college_id', 'college_campuses.campus_id'], name='fk_course_offerings_college_id_campus_id_college_campuses', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_status_id'], ['course_statuses.id'], name=op.f('fk_course_offerings_course_status_id_course_statuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_course_offerings_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_course_offerings_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('fk_course_offerings_qualification_id_qualifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings')),
    sa.UniqueConstraint('college_id', 'campus_id', 'qualification_id', name='uq_course_offerings_college_id_campus_id_qualification_id'),
    sa.UniqueConstraint('course_code', name=op.f('uq_course_offerings_course_code'))
    )
    op.create_index('ix_course_offerings_college_id_campus_id', 'course_offerings', ['college_id', 'campus_id'], unique=False)
    op.create_table('trainer_availability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.BigInteger(), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('location_type', sa.Text(), nullable=True),
    sa.Column('class_type', sa.Enum('THEORY', 'PRACTICAL', name='class_type'), nullable=False),
    sa.Column('working_time_start', sa.Time(), nullable=False),
    sa.Column('working_time_end', sa.Time(), nullable=False),
    sa.Column('monday', sa.Enum('NOT_AVAILABLE', 'PHYSICAL', 'VIRTUAL', name='weekday_mode'), nullable=False),
    sa.Column('tuesday', sa.Enum('NOT_AVAILABLE', 'PHYSICAL', 'VIRTUAL', name='weekday_mode'), nullable=False),
    sa.Column('wednesday', sa.Enum('NOT_AVAILABLE', 'PHYSICAL', 'VIRTUAL', name='weekday_mode'), nullable=False),
    sa.Column('thursday', sa.Enum('NOT_AVAILABLE', 'PHYSICAL', 'VIRTUAL', name='weekday_mode'), nullable=False),
    sa.Column('friday', sa.Enum('NOT_AVAILABLE', 'PHYSICAL', 'VIRTUAL', name='weekday_mode'), nullable=False),
    sa.CheckConstraint('working_time_end > working_time_start', name=op.f('ck_trainer_availability_working_time_ordered')),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_trainer_availability_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_trainer_availability_trainer_id_trainers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_availability')),
    sa.UniqueConstraint('trainer_id', 'campus_id', 'class_type', 'working_time_start', name='uq_trainer_availability_trainer_id_campus_id_class_type_start')
    )
    op.create_index('ix_trainer_availability_campus_id', 'trainer_availability', ['campus_id'], unique=False)
    op.create_table('trainer_qualifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.BigInteger(), nullable=False),
    sa.Column('qualification_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('fk_trainer_qualifications_qualification_id_qualifications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_trainer_qualifications_trainer_id_trainers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_qualifications')),
    sa.UniqueConstraint('trainer_id', 'qualification_id', name='uq_trainer_qualifications_trainer_id_qualification_id')
    )
    op.create_index('ix_trainer_qualifications_qualification_id', 'trainer_qualifications', ['qualification_id'], unique=False)
    op.create_table('trainer_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trainer_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_trainer_units_trainer_id_trainers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_trainer_units_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_units')),
    sa.UniqueConstraint('trainer_id', 'unit_id', name='uq_trainer_units_trainer_id_unit_id')
    )
    op.create_index('ix_trainer_units_unit_id', 'trainer_units', ['unit_id'], unique=False)
    op.create_table('import_staged_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('student_id_value', sa.Text(), nullable=True),
    sa.Column('first_name_value', sa.Text(), nullable=True),
    sa.Column('last_name_value', sa.Text(), nullable=True),
    sa.Column('college_value', sa.Text(), nullable=True),
    sa.Column('campus_value', sa.Text(), nullable=True),
    sa.Column('qualification_value', sa.Text(), nullable=True),
    sa.Column('coe_status_value', sa.Text(), nullable=True),
    sa.Column('proposed_start_date_value', sa.Text(), nullable=True),
    sa.Column('proposed_end_date_value', sa.Text(), nullable=True),
    sa.Column('personal_email_value', sa.Text(), nullable=True),
    sa.Column('primary_phone_value', sa.Text(), nullable=True),
    sa.Column('resolved_college_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_campus_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_qualification_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_offering_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('READY', 'NEEDS_CORRECTION', 'DUPLICATE', 'UNMATCHED_REFERENCE', 'EXCLUDED_BY_USER', name='staged_row_status'), nullable=False),
    sa.Column('duplicate_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('corrected', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_import_staged_rows_import_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_campus_id'], ['campuses.id'], name=op.f('fk_import_staged_rows_resolved_campus_id_campuses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_college_id'], ['colleges.id'], name=op.f('fk_import_staged_rows_resolved_college_id_colleges'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_offering_id'], ['course_offerings.id'], name=op.f('fk_import_staged_rows_resolved_offering_id_course_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_qualification_id'], ['qualifications.id'], name=op.f('fk_import_staged_rows_resolved_qualification_id_qualifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_staged_rows')),
    sa.UniqueConstraint('import_batch_id', 'source_row_number', name='uq_import_staged_rows_import_batch_id_source_row_number')
    )
    op.create_index('ix_import_staged_rows_import_batch_id_status', 'import_staged_rows', ['import_batch_id', 'status'], unique=False)
    op.create_table('offering_duration_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('duration_weeks > 0', name=op.f('ck_offering_duration_options_duration_weeks_positive')),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_offering_duration_options_course_offering_id_course_offerings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offering_duration_options')),
    sa.UniqueConstraint('course_offering_id', 'duration_weeks', name='uq_offering_duration_options_course_offering_id_duration_weeks')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.Text(), nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('intake', sa.Text(), nullable=False),
    sa.Column('expected_class_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_student_groups_course_offering_id_course_offerings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_groups')),
    sa.UniqueConstraint('group_code', name=op.f('uq_student_groups_group_code'))
    )
    op.create_table('import_row_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_staged_row_id', sa.BigInteger(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('issue_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['import_staged_row_id'], ['import_staged_rows.id'], name=op.f('fk_import_row_issues_import_staged_row_id_import_staged_rows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_issues'))
    )
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('student_group_id', sa.BigInteger(), nullable=True),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('course_duration_option_id', sa.BigInteger(), nullable=True),
    sa.Column('college_email', postgresql.CITEXT(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('coe_status', sa.Enum('COE', 'NON_COE', name='coe_status'), nullable=False),
    sa.Column('proposed_start_date', sa.Date(), nullable=False),
    sa.Column('proposed_end_date', sa.Date(), nullable=False),
    sa.Column('actual_course_duration_weeks', sa.Integer(), sa.Computed('(round((proposed_end_date - proposed_start_date + 1) / 7.0))::integer', persisted=True), nullable=False),
    sa.Column('ct_student', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('personal_email', postgresql.CITEXT(), nullable=True),
    sa.Column('primary_phone', sa.Text(), nullable=True),
    sa.Column('primary_country', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_students_soft_delete_metadata_complete')),
    sa.CheckConstraint('proposed_end_date > proposed_start_date', name=op.f('ck_students_course_dates_ordered')),
    sa.ForeignKeyConstraint(['course_duration_option_id'], ['offering_duration_options.id'], name=op.f('fk_students_course_duration_option_id_offering_duration_options'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_students_course_offering_id_course_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_students_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_students_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], name=op.f('fk_students_student_group_id_student_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('student_id', name=op.f('uq_students_student_id'))
    )
    op.create_index('ix_students_course_offering_id', 'students', ['course_offering_id'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_students_last_name_first_name', 'students', ['last_name', 'first_name'], unique=False)
    op.create_index('ix_students_student_group_id', 'students', ['student_group_id'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('timetable_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_reference', sa.Text(), nullable=False),
    sa.Column('student_group_id', sa.BigInteger(), nullable=False),
    sa.Column('course_offering_id', sa.BigInteger(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('class_size_override', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_timetable_plans_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], name=op.f('fk_timetable_plans_course_offering_id_course_offerings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_timetable_plans_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_timetable_plans_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_group_id'], ['student_groups.id'], name=op.f('fk_timetable_plans_student_group_id_student_groups'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_plans')),
    sa.UniqueConstraint('plan_reference', name=op.f('uq_timetable_plans_plan_reference'))
    )
    op.create_table('timetable_unit_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timetable_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('mode_of_delivery', sa.Enum('PHYSICAL', 'VIRTUAL', name='mode_of_delivery'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_timetable_unit_deliveries_delivery_dates_ordered')),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_timetable_unit_deliveries_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_timetable_unit_deliveries_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_timetable_unit_deliveries_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timetable_plan_id'], ['timetable_plans.id'], name=op.f('fk_timetable_unit_deliveries_timetable_plan_id_timetable_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_timetable_unit_deliveries_unit_id_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_unit_deliveries')),
    sa.UniqueConstraint('timetable_plan_id', 'unit_id', name='uq_timetable_unit_deliveries_timetable_plan_id_unit_id')
    )
    op.create_index('ix_timetable_unit_deliveries_start_date_end_date', 'timetable_unit_deliveries', ['start_date', 'end_date'], unique=False)
    op.create_table('timetable_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timetable_unit_delivery_id', sa.BigInteger(), nullable=False),
    sa.Column('session_type', sa.Enum('THEORY', 'PRACTICAL', 'ADDITIONAL', name='session_type'), nullable=False),
    sa.Column('session_title', sa.Text(), nullable=True),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', name='weekday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('trainer_id', sa.BigInteger(), nullable=True),
    sa.Column('trainer_name_text', sa.Text(), nullable=True),
    sa.Column('facility_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_mode', sa.Enum('PHYSICAL', 'VIRTUAL', name='mode_of_delivery'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_id', sa.BigInteger(), nullable=True),
    sa.Column('delete_reason_detail', sa.Text(), nullable=True),
    sa.Column('recovery_deadline', sa.Date(), nullable=True),
    sa.CheckConstraint("session_type <> 'ADDITIONAL' OR delivery_mode = 'VIRTUAL'", name=op.f('ck_timetable_sessions_additional_sessions_are_virtual')),
    sa.CheckConstraint("session_type = 'ADDITIONAL' OR trainer_name_text IS NULL", name=op.f('ck_timetable_sessions_free_text_trainer_only_for_additional')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_timetable_sessions_session_times_ordered')),
    sa.CheckConstraint('is_deleted = false OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL AND delete_reason_id IS NOT NULL AND recovery_deadline IS NOT NULL)', name=op.f('ck_timetable_sessions_soft_delete_metadata_complete')),
    sa.ForeignKeyConstraint(['delete_reason_id'], ['reason_codes.id'], name=op.f('fk_timetable_sessions_delete_reason_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], name=op.f('fk_timetable_sessions_deleted_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_timetable_sessions_facility_id_facilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timetable_unit_delivery_id'], ['timetable_unit_deliveries.id'], name=op.f('fk_timetable_sessions_timetable_unit_delivery_id_timetable_unit_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_timetable_sessions_trainer_id_trainers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_sessions'))
    )
    op.create_index('ix_timetable_sessions_facility_id_weekday', 'timetable_sessions', ['facility_id', 'weekday'], unique=False, postgresql_where=sa.text('facility_id IS NOT NULL'))
    op.create_index('ix_timetable_sessions_timetable_unit_delivery_id', 'timetable_sessions', ['timetable_unit_delivery_id'], unique=False)
    op.create_index('ix_timetable_sessions_trainer_id_weekday', 'timetable_sessions', ['trainer_id', 'weekday'], unique=False, postgresql_where=sa.text('trainer_id IS NOT NULL'))
    op.create_table('timetable_clash_overrides',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timetable_session_id', sa.BigInteger(), nullable=False),
    sa.Column('conflicting_session_id', sa.BigInteger(), nullable=True),
    sa.Column('reason_code_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_timetable_clash_overrides_approved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['conflicting_session_id'], ['timetable_sessions.id'], name=op.f('fk_timetable_clash_overrides_conflicting_session_id_timetable_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reason_code_id'], ['reason_codes.id'], name=op.f('fk_timetable_clash_overrides_reason_code_id_reason_codes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timetable_session_id'], ['timetable_sessions.id'], name=op.f('fk_timetable_clash_overrides_timetable_session_id_timetable_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_clash_overrides'))
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # MANUAL ADDITION 2 of 3 - Alembic autogenerate does not handle views.
    #
    # DBQ-11 approved five weekday columns on trainer_availability, matching the
    # source spreadsheet and the Page 3 grid. That makes the weekday a COLUMN
    # rather than a value, so "is this trainer free on the session's weekday?"
    # cannot be a single indexed predicate.
    #
    # This view unpivots the five columns into rows. Page 3 reads the table;
    # TT-06 clash checking and TRN-01/02 availability search read the view. It
    # stores nothing of its own and therefore cannot drift from the table.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE VIEW trainer_availability_days AS
        SELECT a.id            AS availability_id,
               a.trainer_id,
               a.campus_id,
               a.class_type,
               a.working_time_start,
               a.working_time_end,
               d.weekday,
               d.mode_of_delivery
        FROM trainer_availability AS a
        CROSS JOIN LATERAL (
            VALUES ('MONDAY'::weekday,    a.monday),
                   ('TUESDAY'::weekday,   a.tuesday),
                   ('WEDNESDAY'::weekday, a.wednesday),
                   ('THURSDAY'::weekday,  a.thursday),
                   ('FRIDAY'::weekday,    a.friday)
        ) AS d(weekday, mode_of_delivery)
        """
    )


def downgrade() -> None:
    # MANUAL ADDITION 3 of 3 (part a) - the view depends on
    # trainer_availability, so it must go before the tables.
    op.execute("DROP VIEW IF EXISTS trainer_availability_days")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_clash_overrides')
    op.drop_index('ix_timetable_sessions_trainer_id_weekday', table_name='timetable_sessions', postgresql_where=sa.text('trainer_id IS NOT NULL'))
    op.drop_index('ix_timetable_sessions_timetable_unit_delivery_id', table_name='timetable_sessions')
    op.drop_index('ix_timetable_sessions_facility_id_weekday', table_name='timetable_sessions', postgresql_where=sa.text('facility_id IS NOT NULL'))
    op.drop_table('timetable_sessions')
    op.drop_index('ix_timetable_unit_deliveries_start_date_end_date', table_name='timetable_unit_deliveries')
    op.drop_table('timetable_unit_deliveries')
    op.drop_table('timetable_plans')
    op.drop_index('ix_students_student_group_id', table_name='students', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_students_last_name_first_name', table_name='students')
    op.drop_index('ix_students_course_offering_id', table_name='students', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('students')
    op.drop_table('import_row_issues')
    op.drop_table('student_groups')
    op.drop_table('offering_duration_options')
    op.drop_index('ix_import_staged_rows_import_batch_id_status', table_name='import_staged_rows')
    op.drop_table('import_staged_rows')
    op.drop_index('ix_trainer_units_unit_id', table_name='trainer_units')
    op.drop_table('trainer_units')
    op.drop_index('ix_trainer_qualifications_qualification_id', table_name='trainer_qualifications')
    op.drop_table('trainer_qualifications')
    op.drop_index('ix_trainer_availability_campus_id', table_name='trainer_availability')
    op.drop_table('trainer_availability')
    op.drop_index('ix_course_offerings_college_id_campus_id', table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index('ix_user_activity_records_user_id_occurred_at', table_name='user_activity_records')
    op.drop_index('ix_user_activity_records_occurred_at', table_name='user_activity_records')
    op.drop_table('user_activity_records')
    op.drop_table('trainers')
    op.drop_table('reason_code_contexts')
    op.drop_table('qualification_units')
    op.drop_table('import_batches')
    op.drop_table('facilities')
    op.drop_table('college_campuses')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_table('reason_codes')
    op.drop_table('qualifications')
    op.drop_table('course_statuses')
    op.drop_table('colleges')
    op.drop_table('campuses')
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # MANUAL ADDITION 3 of 3 (part b) - Alembic creates enum types implicitly
    # with the tables that use them, but drop_table does NOT drop them. Without
    # this, `downgrade base` then `upgrade head` fails with "type already
    # exists" - which is exactly what the rebuild test exercises.
    # ------------------------------------------------------------------
    for enum_name in (
        "access_decision",
        "ms_sign_in_result",
        "activity_result",
        "activity_action",
        "staged_row_status",
        "session_type",
        "class_type",
        "weekday",
        "weekday_mode",
        "mode_of_delivery",
        "uoc_type",
        "coe_status",
        "account_status",
        "data_editor_assignment",
        "access_level",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # `citext` is left installed: it is a database-level extension that other
    # schemas could rely on, and dropping it is not this migration's business.
