import type { Campus, College } from '@/types/reference';
import { daysBetween } from './format';

/**
 * Generated student values (SRS 6.3 / SST-03).
 *
 * SST-03 requires TDMS to generate Intake, Group, Qualification Code, State,
 * College Email and the calculated duration "only from approved rules and
 * source data". The approved rules have not been supplied to the frontend, and
 * OD-08 explicitly keeps the week calculation open.
 *
 * The functions below are therefore marked PROVISIONAL. They exist so the
 * generated fields behave like generated fields in the prototype; they are not
 * an approved business rule and the interface says so wherever they are used.
 */

export const PROVISIONAL_GENERATION_NOTE =
  'Generated by a provisional prototype rule. The approved generation rule has not been supplied yet.';

/**
 * OD-08: whether course weeks are counted using inclusive or exclusive dates is
 * an open decision. The prototype uses exclusive counting and labels the value
 * as awaiting approval - it does not present the result as final.
 */
export const WEEK_CALCULATION_METHOD: 'inclusive' | 'exclusive' = 'exclusive';

const MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

/** PROVISIONAL: intake period taken from the proposed start date. */
export function deriveIntake(proposedStartDate: string): string {
  if (!proposedStartDate) return '';
  const [year, month] = proposedStartDate.split('-');
  const monthIndex = Number.parseInt(month ?? '', 10) - 1;
  if (!year || Number.isNaN(monthIndex) || !MONTHS[monthIndex]) return '';
  return `${MONTHS[monthIndex]}-${year}`;
}

/** PROVISIONAL: group built from qualification, campus and intake. */
export function deriveGroup(params: {
  qualificationCode: string;
  campus: Campus | undefined;
  proposedStartDate: string;
}): string {
  const { qualificationCode, campus, proposedStartDate } = params;
  const intake = deriveIntake(proposedStartDate);
  if (!qualificationCode || !campus || !intake) return '';
  const campusToken = campus.campusName.replace(/[^A-Za-z]/g, '').slice(0, 3).toUpperCase();
  return `${qualificationCode}-${campusToken}-${intake.replace('-', '')}`;
}

/**
 * SRS 6.3: the proposed college email is created from the Student ID and the
 * approved college domain. The value is generated but remains editable.
 */
export function deriveCollegeEmail(studentId: string, college: College | undefined): string {
  if (!studentId || !college) return '';
  return `${studentId.toLowerCase()}@${college.emailDomain}`;
}

/** SRS 6.3: State is generated from the selected campus. */
export function deriveState(campus: Campus | undefined): string {
  return campus?.state ?? '';
}

/**
 * PROVISIONAL (OD-08): Actual Course Duration in whole weeks.
 * Returns 0 when either date is missing or the range is invalid.
 */
export function deriveActualCourseDuration(proposedStartDate: string, proposedEndDate: string): number {
  if (!proposedStartDate || !proposedEndDate) return 0;
  const days = daysBetween(proposedStartDate, proposedEndDate);
  if (days <= 0) return 0;
  const countedDays = WEEK_CALCULATION_METHOD === 'inclusive' ? days + 1 : days;
  return Math.round(countedDays / 7);
}

/**
 * SRS 6.3: Course Duration Option is "hidden when the approved CT rule says it
 * is not required". OD-08 keeps that rule open, so the prototype always shows
 * the field, marks it Conditional and explains why it cannot be hidden yet.
 */
export const COURSE_DURATION_OPTION_RULE_PENDING = true;

/** Chooses the approved duration option closest to the calculated duration. */
export function suggestCourseDurationOption(
  actualCourseDuration: number,
  durationOptions: number[],
): number | null {
  if (!actualCourseDuration || durationOptions.length === 0) return null;
  return durationOptions.reduce((closest, option) =>
    Math.abs(option - actualCourseDuration) < Math.abs(closest - actualCourseDuration) ? option : closest,
  );
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export function isValidEmail(value: string): boolean {
  return EMAIL_PATTERN.test(value.trim());
}
